Integration specs for views
elmar8287/blog_app pull request #12
Opened 2021-12-23 15:03 UTC by elmar8287

Use Capybara to write integration tests for each view in your project.

for:

- Login page
- User index page
- User show page
- User post index page
- Post show page

2021-12-23 17:34 UTC, DeliceLydia requested changes
## Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there! my major highlights for your projects :
- Commits messages are descriptive
- Shout out to the good README



## Required Changes ♻️
_Check the comments under the review._



### Have fun while coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-23 17:34 UTC, DeliceLydia commented on spec/views/posts/index_posts_spec.rb
> +end
- [ ] Please fix your views errors all are failing, this is an example
![view](https://user-images.githubusercontent.com/44745855/147273578-f5441209-2ec3-4e4d-ae8f-5dada59eb409.png)

![v2](https://user-images.githubusercontent.com/44745855/147273649-93045549-2f2b-4a96-9068-044b43253edf.png)

![v1](https://user-images.githubusercontent.com/44745855/147273727-f29d58bb-b9b3-4d0c-a5d2-af79842313f9.png)

![v0](https://user-images.githubusercontent.com/44745855/147273791-44974516-19b4-41db-a22d-2fab23ed298c.png)

2021-12-23 17:34 UTC, DeliceLydia commented on spec/views/posts/show_posts_spec.rb
> +end
- [ ] 43 tests are failing please fix them
![v](https://user-images.githubusercontent.com/44745855/147273992-4503b4a2-1dc0-4afb-84a9-7e7c8c741d23.png)

2021-12-25 20:54 UTC, descholar-ceo approved these changes
Hi @elmar8287 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-25 20:55 UTC, merged

2021-12-25 20:55 UTC, elmar8287 commented
Thanks for the review! 👍